a.exe: main.c obsluga.c funkcje.c opcje.c
		gcc -pedantic -Wall main.c obsluga.c funkcje.c opcje.c
main.c: main.c
		gcc -Wall -pedantic -c main.c
obsluga.c: obsluga.c
		gcc -Wall -pedantic -c obsluga.c
funkcje.c: funkcje.c
		gcc -Wall -pedantic -c funkcje.c
opcje.c: opcje.c
		gcc -Wall -pedantic -c opcje.c
