a.exe: main.c pgmobsluga.c filtry.c opcje.c
		gcc -pedantic -Wall main.c pgmobsluga.c filtry.c opcje.c
main.c: main.c
		gcc -Wall -pedantic -c main.c
pgmobsluga.c: pgmobsluga.c
		gcc -Wall -pedantic -c pgmobsluga.c
filtry.c: filtry.c
		gcc -Wall -pedantic -c filtry.c
opcje.c: opcje.c
		gcc -Wall -pedantic -c opcje.c